[package]
name = "provider"
version.workspace = true
edition.workspace = true

[features]
default = ["http"]
http = ["transport/http"]
ws = ["transport/ws"]

[dependencies]
network = { path = "../network" }
rpc-client = { path = "../rpc-client" }
transport = { path = "../transport", default-features = false }

[lints]
workspace = true
