[package]
name = "chain-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
chain-contract = { path = "../contract" }
indexing = { path = "../../indexing" }
json-rpc = { path = "../../../packages/json-rpc" }
signer = { path = "../../signing/contract" }
transaction-account = { path = "../../transactions/account" }

[dev-dependencies]
futures-executor.workspace = true
signer-local = { path = "../../signing/local" }

[lints]
workspace = true
