[package]
name = "chain-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base = { path = "../base" }
crypto = { path = "../../../packages/crypto" }
wallets = { path = "../../wallets" }
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-eth = { version = "=1.0.22", default-features = false, features = ["serde", "std"] }
futures-util = { version = "=0.3.33", default-features = false, features = ["std"] }
indexing = { path = "../../indexing" }
num-bigint.workspace = true
json-rpc = { path = "../../../packages/json-rpc" }
serde_json = { workspace = true, features = ["raw_value"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
futures-executor.workspace = true

[lints]
workspace = true
