[package]
name = "payment_sdk_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "indexer"
path = "src/indexer.rs"

[dependencies]
wallet-worker = { path = "../apps/wallet" }
chain-ethereum = { path = "../sdk/chains/ethereum" }
signer = { path = "../sdk/signing/contract" }
signer-local = { path = "../sdk/signing/local" }
payment-http = { package = "http", path = "../packages/http" }
indexer-worker = { path = "../apps/indexer" }

tokio = { version = "=1.49.0", features = ["macros", "rt-multi-thread"] }

reqwest = { version = "=0.12.28", default-features = false, features = ["json", "rustls-tls"] }
