[package]
name = "chain-bitcoin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base = { path = "../base" }
crypto = { path = "../../../packages/crypto" }
wallets = { path = "../../wallets" }
bitcoin.workspace = true
futures-util = { version = "=0.3.33", default-features = false, features = ["std"] }
indexing = { path = "../../indexing" }
json-rpc = { path = "../../../packages/json-rpc" }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["time"] }

[dev-dependencies]
futures-executor.workspace = true

[lints]
workspace = true
