[package]
name = "indexing-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base = { path = "../../chains/base" }
http = { path = "../../../packages/http" }
indexing = { path = ".." }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
url = "=2.5.8"

[dev-dependencies]
axum = "=0.8.4"
tokio = { workspace = true, features = ["net"] }
tower = { version = "=0.5.2", features = ["util"] }

[lints]
workspace = true
