[package]
name = "signer-bitcoin"
version.workspace = true
edition.workspace = true

[dependencies]
network = { path = "../network" }
network-bitcoin = { path = "../network-bitcoin" }
primitives = { path = "../primitives" }
signer = { path = "../signer" }

[dev-dependencies]
signer-local = { path = "../signer-local" }

[lints]
workspace = true
