[package]
name = "indexing-rocksdb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
base = { path = "../../chains/base" }
bincode = { version = "=2.0.1", default-features = false, features = ["derive", "std"] }
indexing = { path = ".." }
storage = { path = "../../../packages/storage" }
storage-rocksdb = { path = "../../../packages/storage/rocksdb" }

[dev-dependencies]
futures-executor.workspace = true
tempfile = "=3.27.0"

[lints]
workspace = true
