[package]
name = "indexer-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = "=0.8.4"
chain-identity = { path = "../../sdk/chains/identity" }
chain-bitcoin = { path = "../../sdk/chains/bitcoin" }
chain-ethereum = { path = "../../sdk/chains/ethereum" }
clap = { version = "=4.5.50", features = ["derive", "env"] }
http = { path = "../../packages/http" }
indexing = { path = "../../sdk/indexing" }
json-rpc = { path = "../../packages/json-rpc" }
serde = { version = "=1.0.219", features = ["derive"] }
serde_json.workspace = true
storage = { path = "../../sdk/storage" }
storage-rocksdb = { path = "../../sdk/storage/rocksdb" }
telemetry = { path = "../../packages/telemetry" }
tokio = { workspace = true, features = ["net", "signal", "sync", "time"] }
tracing = "=0.1.41"
tracing-subscriber = { version = "=0.3.20", features = ["env-filter", "fmt", "json"] }
url = "=2.5.8"
uuid.workspace = true

[dev-dependencies]
bitcoin.workspace = true
tower = { version = "=0.5.2", features = ["util"] }

[lints]
workspace = true
