[package]
name = "payment-sdk"
version.workspace = true
edition.workspace = true

[workspace]
members = [
    "crates/network",
    "crates/network-bitcoin",
    "crates/network-ethereum",
    "crates/primitives",
    "crates/provider",
    "crates/rpc-client",
    "crates/signer",
    "crates/signer-bitcoin",
    "crates/signer-ethereum",
    "crates/signer-local",
    "crates/transport",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.lints.rust]
unsafe_code = "forbid"

[features]
default = ["http"]
http = ["provider/http", "transport/http"]
ws = ["provider/ws", "transport/ws"]

[dependencies]
network = { path = "crates/network" }
network-bitcoin = { path = "crates/network-bitcoin" }
network-ethereum = { path = "crates/network-ethereum" }
primitives = { path = "crates/primitives" }
provider = { path = "crates/provider", default-features = false }
signer = { path = "crates/signer" }
signer-bitcoin = { path = "crates/signer-bitcoin" }
signer-ethereum = { path = "crates/signer-ethereum" }
signer-local = { path = "crates/signer-local" }
transport = { path = "crates/transport", default-features = false }

[[example]]
name = "ethereum_http"
required-features = ["http"]

[[example]]
name = "ethereum_ws"
required-features = ["ws"]

[[example]]
name = "bitcoin_http"
required-features = ["http"]

[lints]
workspace = true
