[package]
name = "indexing-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
indexing = { path = ".." }
tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }


[lints]
workspace = true
