[package]
name = "wallet-worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = "=0.8.4"
base = { path = "../../sdk/chains/base" }
chain-bitcoin = { path = "../../sdk/chains/bitcoin" }
chain-ethereum = { path = "../../sdk/chains/ethereum" }
http-support = { package = "http", path = "../../packages/http" }
indexing = { path = "../../sdk/indexing" }
indexing-http = { path = "../../sdk/indexing/http" }
json-rpc = { path = "../../packages/json-rpc" }
wallets = { path = "../../sdk/wallets" }
hex.workspace = true
serde = { version = "=1.0.219", features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "signal", "time"] }

[dev-dependencies]
http-body-util = "=0.1.4"
tower = { version = "=0.5.2", features = ["util"] }

[lints]
workspace = true
